lang: en
title: openSUSE Monitor
title_short: Monitor
description: Monitoring of openSUSE Infrastructure
email: admin@opensuse.org
copyright: '© 2021 openSUSE contributors'
baseurl: ""
url: "https://monitor.opensuse.org"

navbar_links:
  -
    link: https://monitor.opensuse.org/icingaweb2/
    text: Monitoring
  -
    link: https://status.opensuse.org/
    text: Status
  -
    link: https://monitor.opensuse.org/grafana/
    text: Grafana
#  -
#    link: https://graylog.opensuse.org/
#    text: Graylog

footer_links:
  -
    text: Source Code
    link: https://github.com/openSUSE/monitor-o-o
  -
    text: License
    link: https://github.com/openSUSE/monitor-o-o/blob/master/COPYING

# Only edit below if you know what you are doing!

defaults:
  -
    scope:
      path: "*.html"
    values:
      layout: "default"
  -
    scope:
      path: "*.md"
    values:
      layout: "markdown"
  -
    scope:
      path: "*.markdown"
    values:
      layout: "markdown"

disable_search: true

theme: jekyll-theme-opensuse
markdown: kramdown

exclude: [README.md, Gemfile, Gemfile.lock, vendor]
