lang: en
title: openSUSE Template
title_short: Template
description: Template for openSUSE Websites
email: admin@opensuse.org
copyright: '© 2020 openSUSE contributors'
baseurl: ""
url: "https://template.opensuse.org"
github_url: "https://github.com/openSUSE/jekyll-template"

navbar_links:
  -
    link: https://www.opensuse.org/
    text: Absolute Link 1
  -
    link: /about/
    text: Relative Link 2

footer_links:
  -
    text: Source Code
    link: https://github.com/openSUSE/jekyll-template
  -
    text: License
    link: https://github.com/openSUSE/jekyll-template/blob/master/COPYING

# Only edit below if you know what you are doing!

defaults:
  -
    scope:
      path: "*.html"
    values:
      layout: "default"
  -
    scope:
      path: "*.md"
    values:
      layout: "markdown"
  -
    scope:
      path: "*.markdown"
    values:
      layout: "markdown"

disable_search: true

theme: jekyll-theme-opensuse
markdown: kramdown

exclude: [README.md, Gemfile, Gemfile.lock, vendor]
